package ylj.mofunk.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ylj.mofunk.model.Entity.ZhiBean;

import ylj.mofunk.dao.ZhiBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig zhiBeanDaoConfig;

    private final ZhiBeanDao zhiBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        zhiBeanDaoConfig = daoConfigMap.get(ZhiBeanDao.class).clone();
        zhiBeanDaoConfig.initIdentityScope(type);

        zhiBeanDao = new ZhiBeanDao(zhiBeanDaoConfig, this);

        registerDao(ZhiBean.class, zhiBeanDao);
    }
    
    public void clear() {
        zhiBeanDaoConfig.clearIdentityScope();
    }

    public ZhiBeanDao getZhiBeanDao() {
        return zhiBeanDao;
    }

}
